version: '3'
services:
crud_go:
build:
context: .
dockerfile: Dockerfile
environment:
- MONGODB_URL=mongodb://mongodb:27017
- MONGODB_USER_DB=users
- JWT_SECRET_KEY=g@A$zX!c9TqP1vYk&bNlM7oR5uJdE2iW
ports:
- "8080:8080"
depends_on:
- mongodb
networks:
- meu_crud_network

mongodb:
image: mongo
ports:
- "27017:27017"
networks:
- meu_crud_network

networks:
meu_crud_network:
